### ISSUE TITLE
Tracking Module

### ISSUE THREAD

**Issue by piq9117** [piq9117/bs-mailgun#4]
Write bindings for the tracking module

- [x] info
- [x] update open tracking
- [x] update click tracking
- [x] update subscription tracking
